pulls: # will only affect pull requests
  # Number of days of inactivity before an issue becomes stale
  daysUntilStale: 7
  # Number of days of staleness before a stale issue is closed
  daysUntilClose: 7 # 14 days of inactivity
  # Issues with these labels will never be considered stale
  exemptLabels:
    - pinned
  # Label to use when marking an issue as stale
  staleLabel: stale
  # Comment to post when marking an issue as stale. Set to `false` to disable
  markComment: >
    This pull request has been automatically marked as stale because it has not had recent activity.
    It will be closed if no further activity occurs.
    Thank you for your contributions.
  # Comment to post when closing a stale issue. Set to `false` to disable
  closeComment: >
    This pull request has been automatically closed due to inactivity.
