name: Test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV: test
      GIN_MODE: test
      GOLANG_VERSION: '1.25'
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          check-latest: true
          cache: true

      - name: test with coverage
        run: make test

